# .mockery.yml
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  github.com/go-ble/ble:
    interfaces:
      Addr:
        config:
          dir: "internal/testutils/mocks"
          outpkg: mocks
      Advertisement:
        config:
          dir: "internal/testutils/mocks"
          outpkg: "mocks"
          mockname: BleAdvertisementMock
          filename: "mock_BleAdvertisement.go"
      Device:
        config:
          dir: "internal/testutils/mocks"
          outpkg: "mocks"
      Client:
        config:
          dir: "internal/testutils/mocks"
          outpkg: "mocks"
  github.com/srg/blim/internal/device:
    interfaces:
      Advertisement:
        config:
          dir: "internal/testutils/mocks"
          outpkg: mocks
          mockname: DeviceAdvertisementMock
