packages:
  github.com/go-ble/ble:
    config:
      dir: "internal/testutils/mocks/goble"
    interfaces:
      Addr:
        config:
          filename: "mock_BleClient.go"
      Advertisement:
        config:
          filename: "mock_BleAdvertisement.go"
      Device:
        config:
          filename: "mock_BleAdvertisement.go"
      Client:
        config:
          filename: "mock_BleClient.go"

  github.com/srg/blim/internal/device:
    config:
      dir: "internal/testutils/mocks/device"
    interfaces:
      Advertisement:
        config:
          filename: "mock_DeviceAdvertisement.go"
